apiVersion: v1
data:
  API_KEY: MjgzMjhiNTQxMTk3NjRlNjMxZjI4MjhhZmVjOTdjM2U4ZDk5N2Q5Nw==
  JWT_SECRET: YmRjYzZmODM4N2VkYTZmNjE1YjYzNzdiNDk2ODdhYjdkYWNiYWM2MjZjMDM0NzQxZDIwM2FiNTFhZTQ4NTA3MQ==
kind: Secret
metadata:
  name: app-secrets
  namespace: backend
type: Opaque