apiVersion: v1
data:
  API_KEY: MjgzMjhiNTQxMTk3NjRlNjMxZjI4MjhhZmVjOTdjM2U4ZDk5N2Q5Nw==
  JWT_SECRET: YmRjYzZmODM4N2VkYTZmNjE1YjYzNzdiNDk2ODdhYjdkYWNiYWM2MjZjMDM0NzQxZDIwM2FiNTFhZTQ4NTA3MQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"app-secrets","namespace":"default"},"spec":{"data":[{"remoteRef":{"key":"eks-app/application","property":"JWT_SECRET"},"secretKey":"JWT_SECRET"},{"remoteRef":{"key":"eks-app/application","property":"API_KEY"},"secretKey":"API_KEY"}],"refreshInterval":"1h","secretStoreRef":{"kind":"ClusterSecretStore","name":"aws-secrets-store"},"target":{"creationPolicy":"Owner","name":"app-secrets"}}}
    reconcile.external-secrets.io/data-hash: 0203dd4456bc6f1847ff04587f1ba30891868ec0bb4c90d7c0d173cb
  creationTimestamp: "2025-07-18T00:50:14Z"
  labels:
    reconcile.external-secrets.io/created-by: 15a01b86b2cec806c162e46e353a65681bc0109cb2a0e99961271f0a
    reconcile.external-secrets.io/managed: "true"
  name: app-secrets
  namespace: default
  ownerReferences:
  - apiVersion: external-secrets.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: app-secrets
    uid: 62e3f3f1-a602-4be0-ac40-03ba9d1303b5
  resourceVersion: "47797"
  uid: 41a91bc8-0247-46c8-9ce2-dfd2ad86b71a
type: Opaque
