apiVersion: v1
data:
  POSTGRES_DB: ZWtzYXBw
  POSTGRES_PASSWORD: NTUyZWQzZDA2MjEyNjA1ZjZlNWRiMjBjNDRmY2RkYzg=
  POSTGRES_USER: ZWtzYWRtaW4=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"db-secrets","namespace":"default"},"spec":{"data":[{"remoteRef":{"key":"eks-app/database","property":"POSTGRES_USER"},"secretKey":"POSTGRES_USER"},{"remoteRef":{"key":"eks-app/database","property":"POSTGRES_PASSWORD"},"secretKey":"POSTGRES_PASSWORD"},{"remoteRef":{"key":"eks-app/database","property":"POSTGRES_DB"},"secretKey":"POSTGRES_DB"}],"refreshInterval":"1h","secretStoreRef":{"kind":"ClusterSecretStore","name":"aws-secrets-store"},"target":{"creationPolicy":"Owner","name":"db-secrets"}}}
    reconcile.external-secrets.io/data-hash: 3fd3020bdf95f6d4997a61216ac85848225cd308a003979d88b62827
  creationTimestamp: "2025-07-18T00:50:14Z"
  labels:
    reconcile.external-secrets.io/created-by: aba4d2a7ff375de2f07c2ec42b7c8d6511251e02ba3fbe39646f3dcc
    reconcile.external-secrets.io/managed: "true"
  name: db-secrets
  namespace: default
  ownerReferences:
  - apiVersion: external-secrets.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: db-secrets
    uid: 16f0b2f8-0d3e-4668-b1f8-9151b8fd5646
  resourceVersion: "47807"
  uid: 604c6428-2299-47bd-8e25-fbefb6b03b3c
type: Opaque
