apiVersion: v1
data:
  POSTGRES_DB: ZWtzYXBw
  POSTGRES_PASSWORD: NTUyZWQzZDA2MjEyNjA1ZjZlNWRiMjBjNDRmY2RkYzg=
  POSTGRES_USER: ZWtzYWRtaW4=
kind: Secret
metadata:
  name: db-secrets
  namespace: backend
type: Opaque